language: python
sudo: required
services:
  - docker

python:
  - "3.6"
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  - pip install -r requirements.txt
script:
  - coverage run -m unittest
after_success:
  - coveralls
  # Build to docker image, and push it
  - docker build -t craigslist-housing .
  - docker tag craigslist-housing:latest pengivan/craigslist-housing
  - docker push pengivan/craigslist-housing